#!/bin/bash

if [ $CODEBUILD_WEBHOOK_EVENT == 'PUSH' ] && [ $CODEBUILD_WEBHOOK_HEAD_REF == 'refs/heads/master' ]; then
  echo 'Deploying app to aws lambda'
  npm run package
  aws lambda update-function-code --function-name Fondo-MNS --zip-file fileb://fondo-mns.zip
fi